// <auto-generated />
namespace GraduationProject.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v01));
        
        string IMigrationMetadata.Id
        {
            get { return "201904201052361_v0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
